from copy import deepcopy
from typing import Any


AGENTS: list[dict[str, Any]] = [
    {
        "id": "intake_agent",
        "label": "Intake Agent",
        "purpose": "Normalize raw partner lifecycle requests into the canonical ticket state.",
        "owns": ["ticket"],
        "reads": ["invocation_payload"],
        "writes": ["ticket", "audit_events"],
        "handoffs": ["rbac_agent"],
        "guardrails": ["Require ticket_id, partner_name, project_case, created_by."],
    },
    {
        "id": "rbac_agent",
        "label": "RBAC Agent",
        "purpose": "Authorize the actor role and action before any workflow mutation.",
        "owns": ["access_result", "visibility"],
        "reads": ["role", "action", "ticket"],
        "writes": ["access_result", "audit_events"],
        "handoffs": ["admin_governance_agent", "access_denied_agent"],
        "guardrails": ["External partner roles only receive external_limited visibility."],
    },
    {
        "id": "admin_governance_agent",
        "label": "Admin Governance Agent",
        "purpose": "Plan admin-center setup for users, departments, review matrix, DD rules, and connectors.",
        "owns": ["admin_plan"],
        "reads": ["ticket", "access_result"],
        "writes": ["admin_plan", "api_contracts", "audit_events"],
        "handoffs": ["policy_agent"],
        "guardrails": ["Admin changes remain planned until execution is explicitly approved."],
    },
    {
        "id": "policy_agent",
        "label": "Critical Policy Agent",
        "purpose": "Enforce critical enterprise governance policies before DD and review work begins.",
        "owns": ["policy_result"],
        "reads": ["ticket", "override_reason", "risk_acceptance"],
        "writes": ["policy_result", "audit_events"],
        "handoffs": ["dd_gate_agent", "policy_blocked_agent"],
        "guardrails": ["No override is accepted without a reason and risk acceptance trail."],
    },
    {
        "id": "dd_gate_agent",
        "label": "DD Gate Agent",
        "purpose": "Apply the No DD Pass -> No Contract Review rule.",
        "owns": ["dd_result", "workflow_status"],
        "reads": ["dd_status", "dd_findings", "policy_result"],
        "writes": ["dd_result", "workflow_status", "audit_events"],
        "handoffs": ["contract_review_agent", "sharepoint_agent"],
        "guardrails": ["Only Pass and Conditional Pass can advance into contract review."],
    },
    {
        "id": "contract_review_agent",
        "label": "Contract Review Agent",
        "purpose": "Create review rounds, reviewer tasks, and department coverage checks.",
        "owns": ["review_plan"],
        "reads": ["ticket", "selected_departments", "contract_signals"],
        "writes": ["review_plan", "workflow_status", "audit_events"],
        "handoffs": ["sharepoint_agent"],
        "guardrails": ["Mandatory departments must be selected before ready_for_review."],
    },
    {
        "id": "sharepoint_agent",
        "label": "SharePoint Agent",
        "purpose": "Plan official SharePoint folders, file actions, and permissions.",
        "owns": ["sharepoint_plan"],
        "reads": ["ticket", "review_plan", "dd_result"],
        "writes": ["sharepoint_plan", "api_contracts", "audit_events"],
        "handoffs": ["lifecycle_agent"],
        "guardrails": ["Partner-facing access is limited to explicitly approved folders."],
    },
    {
        "id": "lifecycle_agent",
        "label": "Lifecycle Agent",
        "purpose": "Plan negotiation, partner portal, and termination lifecycle operations.",
        "owns": ["negotiation_plan", "partner_portal_plan", "termination_plan"],
        "reads": ["ticket", "workflow_status"],
        "writes": ["negotiation_plan", "partner_portal_plan", "termination_plan", "audit_events"],
        "handoffs": ["ai_planning_agent"],
        "guardrails": ["Termination and signing actions remain separate workflow tracks."],
    },
    {
        "id": "ai_planning_agent",
        "label": "AI Planning Agent",
        "purpose": "Plan optional AI operations for DD analysis, contract summary, risk scoring, and checklists.",
        "owns": ["ai_plan"],
        "reads": ["ticket", "review_plan", "dd_result"],
        "writes": ["ai_plan", "api_contracts", "audit_events"],
        "handoffs": ["office365_agent"],
        "guardrails": ["AI operations are advisory and do not bypass deterministic policy gates."],
    },
    {
        "id": "office365_agent",
        "label": "Office365 Agent",
        "purpose": "Plan Microsoft Graph operations for users, groups, mail, calendar, Teams, and files.",
        "owns": ["office365_plan"],
        "reads": ["ticket", "review_plan", "sla_plan"],
        "writes": ["office365_plan", "api_contracts", "audit_events"],
        "handoffs": ["sla_agent"],
        "guardrails": ["Connector actions are represented as planned operations until execution."],
    },
    {
        "id": "sla_agent",
        "label": "SLA Agent",
        "purpose": "Plan reminders, overdue scans, and department-manager escalations.",
        "owns": ["sla_plan"],
        "reads": ["review_plan", "due_date", "priority"],
        "writes": ["sla_plan", "api_contracts", "audit_events"],
        "handoffs": ["execution_agent"],
        "guardrails": ["Escalation plans must preserve the original review task owner."],
    },
    {
        "id": "execution_agent",
        "label": "Execution Planner",
        "purpose": "Order planned API operations into a dry-run execution queue.",
        "owns": ["execution_plan"],
        "reads": ["admin_plan", "sharepoint_plan", "office365_plan", "sla_plan", "ai_plan"],
        "writes": ["execution_plan", "audit_events"],
        "handoffs": ["audit_persistence_agent"],
        "guardrails": ["Every planned external operation requires an audit entry."],
    },
    {
        "id": "audit_persistence_agent",
        "label": "Audit Persistence Agent",
        "purpose": "Plan immutable audit persistence to SharePoint and Admin audit logs.",
        "owns": ["audit_plan"],
        "reads": ["audit_events", "execution_plan"],
        "writes": ["audit_plan"],
        "handoffs": ["dashboard_agent"],
        "guardrails": ["Audit persistence is append-only."],
    },
    {
        "id": "dashboard_agent",
        "label": "Dashboard Agent",
        "purpose": "Build operational counters and queue snapshots for governance monitoring.",
        "owns": ["dashboard_snapshot"],
        "reads": ["ticket", "workflow_status", "review_plan", "sla_plan"],
        "writes": ["dashboard_snapshot", "audit_events"],
        "handoffs": ["ai_summary_agent"],
        "guardrails": ["Dashboard data must not expose internal-only fields to external visibility."],
    },
    {
        "id": "access_denied_agent",
        "label": "Access Denied Agent",
        "purpose": "Return a controlled terminal response when RBAC blocks the actor.",
        "owns": ["workflow_status"],
        "reads": ["access_result", "ticket"],
        "writes": ["workflow_status", "audit_events"],
        "handoffs": ["ai_summary_agent"],
        "guardrails": ["Do not continue to policy, DD, or execution planning after denial."],
    },
    {
        "id": "policy_blocked_agent",
        "label": "Policy Blocked Agent",
        "purpose": "Return a controlled terminal response when a critical policy is violated.",
        "owns": ["workflow_status"],
        "reads": ["policy_result", "ticket"],
        "writes": ["workflow_status", "audit_events"],
        "handoffs": ["ai_summary_agent"],
        "guardrails": ["Do not continue to DD or contract review after a blocking violation."],
    },
    {
        "id": "ai_summary_agent",
        "label": "AI Summary Agent",
        "purpose": "Produce optional user-facing summary text and call memory tools when configured.",
        "owns": ["ai_summary"],
        "reads": ["ticket", "workflow_status", "dashboard_snapshot", "audit_events"],
        "writes": ["ai_summary", "messages"],
        "handoffs": ["tools", "END"],
        "guardrails": ["Fallback to deterministic summaries when LLM credentials are not configured."],
    },
    {
        "id": "tools",
        "label": "Memory Tools",
        "purpose": "Persist and recall long-term memory facts for configured AgentBase memory stores.",
        "owns": ["memory_records"],
        "reads": ["messages", "MEMORY_ID", "MEMORY_STRATEGY_ID"],
        "writes": ["messages", "memory_records"],
        "handoffs": ["ai_summary_agent"],
        "guardrails": ["Do not require memory for deterministic governance execution."],
    },
]


def list_agents() -> list[dict[str, Any]]:
    return deepcopy(AGENTS)


def get_agent(agent_id: str) -> dict[str, Any]:
    for agent in AGENTS:
        if agent["id"] == agent_id:
            return deepcopy(agent)
    raise KeyError(f"Unknown agent: {agent_id}")
